SPICES=('Spices','','turmeric, chilli, Kashmiri chilli, coriander & cumin powder, cumin & mustard seeds, garam masala, sambar powder, tandoori/tikka masala, black pepper, fennel, fenugreek, hing, kasuri methi, chaat masala')
GRO_A = [
 ('Meat, fish & eggs',[('Chicken breast, boneless','1 kg','6 × 150 g; mince one portion for keema'),('Fish fillets (seer, basa, rohu)','450 g','3 × 150 g'),('Prawns, cleaned','150 g','about 300 g with shells'),('Eggs','15','12 used, 3 spare')]),
 ('Dairy',[('Low-fat / high-protein paneer','500 g','400 g for curries, rest for pesarattu & chilla'),('Curd (dahi)','1.5 kg','includes 400 g to hang for Greek-style curd'),('Double-toned milk','500 ml','200 ml used'),('Whey protein','7 scoops','your 52-scoop tub lasts about 7 weeks')]),
 ('Vegetables',[('Onion','1 kg',''),('Tomato','1.25 kg',''),('Mixed vegetables (beans, carrot, broccoli, cabbage)','750 g','3 × 250 g'),('Sambar vegetables (drumstick, brinjal, pumpkin, okra)','300 g',''),('Spinach','1 bunch (≈250 g)',''),('Capsicum','2 medium',''),('Cucumber','3',''),('Green peas (frozen ok)','100 g',''),('Ginger','100 g',''),('Garlic','1 bulb',''),('Green chillies','50 g',''),('Curry leaves, coriander, mint','1 bunch each',''),('Lemons','4','')]),
 ('Fruit',[('Bananas','6','one per training day'),('Apple','1',''),('Papaya','1 small','150 g used; eat the rest'),('Pomegranate','1 small','100 g arils')]),
 ('Grains, dals & snacks',[('Rice (sona masoori or any)','500 g',''),('Basmati rice','100 g',''),('Whole wheat atta','150 g',''),('Rolled oats','120 g',''),('Idli batter','250 g','or grind at home'),('Toor dal','100 g',''),('Whole green moong','200 g','pesarattu + sprouts'),('Yellow moong dal','60 g',''),('Soya chunks / granules','150 g',''),('Kala chana','50 g',''),('Roasted chana','50 g',''),('Makhana','30 g',''),('Cashews','10 g','')]),
 ('Pantry (check stock)',[('Cooking oil','100 ml','about 5 g per meal'),('Coconut oil, ghee','small',''),('Tamarind','30 g',''),SPICES]),
]
GRO_B = [
 ('Meat & eggs',[('Chicken breast, boneless','1 kg','malai ×2, dumplings 200 g, coriander chicken 180 g, kabab, tandoori'),('Eggs','20','14 whole + whites of 5 more')]),
 ('Dairy',[('Low-fat / high-protein paneer','900 g','pasta 200, tikka bowl 200, palak 200, fried rice 150, plus extras'),('Curd (dahi)','1.3 kg','includes 600 g to hang for Greek-style curd'),('Double-toned milk','500 ml','300 ml used'),('Mozzarella','30 g',''),('Butter','small','5 g'),('Whey protein','7 scoops','')]),
 ('Vegetables',[('Onion','750 g',''),('Tomato','750 g',''),('Okra','150 g',''),('Cabbage','1 small head','for dumpling leaves; use the rest in stir-fries'),('Capsicum','1 large',''),('Mixed vegetables (beans, carrot, corn, peas)','450 g',''),('Sambar vegetables','300 g',''),('Spinach','1 bunch (≈250 g)',''),('Cucumber','5',''),('Garlic','2 bulbs','reels use a lot of garlic'),('Coriander','3 bunches','green soya rice + coriander chicken'),('Mint','1 bunch',''),('Ginger','100 g',''),('Green chillies','50 g',''),('Spring onion','1 bunch',''),('Lemons','3','')]),
 ('Fruit',[('Bananas','6',''),('Apples','2',''),('Papaya','1 small',''),('Pomegranate','1 small','')]),
 ('Grains, dals & snacks',[('Rice','350 g',''),('Whole wheat atta','150 g',''),('Rolled oats','120 g',''),('Macaroni','250 g pack','60 g used'),('Idli batter','250 g',''),('Toor dal','100 g',''),('Whole green moong','200 g',''),('Yellow moong dal','60 g',''),('Soya chunks','200 g',''),('Rice flour, cornflour','50 g each',''),('Sesame seeds','10 g',''),('Cashews','5 g','')]),
 ('Sauces & pantry',[('Gochujang (or schezwan sauce)','1 small tub','30 g used'),('Soy sauce','small bottle',''),('Chicken kabab masala','1 packet',''),('Byadagi dried chillies','small pack','egg ghee roast'),('Cooking oil, ghee','check stock',''),('Tamarind','20 g',''),SPICES]),
]
