# key -> (category, ingredients list, steps list, tip)
T = {
'sambar':('South Indian basics',
 ['30 g toor dal','100 g sambar vegetables (drumstick, brinjal, pumpkin, okra)','20 g onion or 4 shallots','30 g tomato','5 g tamarind (small marble)','1 tsp sambar powder, pinch turmeric and hing','3 g oil, mustard seeds, curry leaves, 1 dried red chilli'],
 ['Pressure-cook the dal with turmeric for 3 whistles, then mash.','Simmer the vegetables, onion and tomato in tamarind water with sambar powder and salt for 8–10 min.','Add the dal and simmer 5 min.','Temper oil with mustard, hing, curry leaves and red chilli; pour over.'],
 'Make 3 bowls on Sunday (Mon, Wed, Thu). Keeps 3 days in the fridge; freeze Thursday\'s.'),
'idli':('Breakfast',
 ['150 g idli batter (3 idlis)','1 bowl protein sambar','1 egg'],
 ['Steam the idlis 10–12 min.','Boil the egg 9 min, cool and peel.','Serve with hot sambar.'],
 'Coconut chutney adds about 100 kcal per 2 tbsp; tomato or pudina chutney is almost free.'),
'pesarattu_p':('Breakfast',
 ['60 g whole green moong, soaked 6–8 h','1 green chilli, 5 g ginger, ½ tsp cumin, salt','40 g paneer, grated, + a little chopped onion','8 g oil (dosa + chutney)','Chutney: 100 g tomato, 5 g ginger, 1 dried red chilli'],
 ['Grind the soaked moong with chilli, ginger, cumin and salt to a pourable batter.','Spread 2 thin dosas on a hot tawa with 5 g oil.','Sprinkle paneer and onion on top, fold and cook through.','Chutney: sauté tomato, ginger and chilli in 3 g oil, then blend with salt.'],
 'Soak the moong the night before.'),
'pesarattu_e':('Breakfast',
 ['Same pesarattu batter and chutney as above, no paneer','1 egg'],
 ['Make 2 pesarattu as above.','Boil the egg, or crack it over the dosa while it cooks (egg pesarattu).'],''),
'bhurji':('Breakfast',
 ['2 whole eggs + 3 egg whites','50 g onion, 50 g tomato, 1 green chilli','Pinch turmeric, ½ tsp chilli powder, coriander leaves','3 g oil','1 chapati (30 g atta, no ghee)'],
 ['Sauté onion and chilli in oil until soft, add tomato and spices and cook 2 min.','Pour in the whisked eggs and scramble on low heat until just set.','Serve with a hot chapati.'],'Keep the yolks from the 3 whites for another day, or skip them.'),
'chilla':('Breakfast',
 ['60 g yellow moong dal, soaked 2–3 h','50 g paneer, crumbled','¼ small onion, pinch cumin and chilli','5 g oil','100 g low-fat curd on the side'],
 ['Blend the moong with a little water and salt to a pancake batter.','Spread on a hot pan with oil, scatter paneer and onion.','Cook both sides until golden. Serve with curd.'],'Handbook p.40.'),
'oatsbowl':('Breakfast',
 ['65 g rolled oats','100 g Greek yogurt or hung curd','100 g pomegranate arils','1 egg'],
 ['Boil the egg 8–10 min.','Layer yogurt, oats and pomegranate in a bowl.','Serve with the halved egg.'],'Handbook p.7. For a warm version, microwave the oats with yogurt for 60–90 s.'),
'oatswhey':('Breakfast',
 ['50 g rolled oats','200 ml double-toned milk','1 scoop of your whey (38.5 g)','150 g papaya, cinnamon'],
 ['Simmer oats in milk 4–5 min until thick.','Cool 1 min, then stir in the whey (too hot and it clumps).','Top with cinnamon; papaya on the side.'],'Handbook p.8, made with a full scoop. On Sunday this replaces the shake.'),
'chx_rice':('Lunch & dinner',
 ['150 g chicken breast','50 g raw rice (150 g cooked)','250 g mixed vegetables','5 g oil, ½ tsp cumin or paprika, salt, pepper'],
 ['Cook the rice.','Sear the seasoned chicken 5–6 min per side in oil; rest and slice.','Steam or sauté the vegetables 5 min.','Assemble over rice.'],'Handbook p.11.'),
'chx_chapati':('Lunch & dinner',
 ['150 g chicken breast','2 chapatis (60 g atta)','250 g mixed vegetables','5 g oil, spices'],
 ['Sear and slice the chicken as for the rice bowl.','Sauté the vegetables.','Serve with warm chapatis.'],'Handbook p.12.'),
'tandoori':('Lunch & dinner',
 ['150 g chicken breast or thigh','100 g low-fat curd, 1 tsp ginger-garlic paste','1 tsp tandoori masala, ½ tsp turmeric, juice of ½ lemon','5 g oil','50 g raw rice (150 g cooked)'],
 ['Marinate chicken in curd, paste, masala, turmeric, lemon and salt for 30 min or overnight.','Grill, broil or air-fry 6–8 min per side (oven: 220 °C, 20 min).','Rest 2 min; serve with rice and onion salad.'],'Handbook p.13. Marinate Thursday night.'),
'tikkamasala':('Lunch & dinner (swap)',
 ['150 g chicken breast','1 small onion, 150 g tomato purée','30 g low-fat curd, 10 g cashews (soaked, blended)','1 tsp ginger-garlic paste, garam masala, chilli, kasuri methi','5 g oil','35 g raw rice (100 g cooked)'],
 ['Sear the chicken cubes 4–5 min; set aside.','Sauté onion and paste, add tomato and spices, cook 8 min.','Stir in curd and cashew paste, add chicken, simmer 8–10 min.'],'Handbook p.15. Swap in for any chicken meal.'),
'keema':('Lunch & dinner',
 ['150 g lean chicken mince','1 small onion, 1 tomato, 50 g green peas','1 tsp ginger-garlic paste, turmeric, chilli, garam masala','5 g oil','35 g raw rice (100 g cooked)'],
 ['Sauté onion golden, add paste, then tomato and spices until thick.','Add mince, break it up, cook 5 min.','Add peas and a splash of water, cover 6–8 min.'],'Handbook p.16. Ask the butcher to mince 150 g of the breast.'),
'fishtikka':('Lunch & dinner',
 ['150 g firm fish (seer/vanjaram, basa)','100 g low-fat curd, 1 tsp ginger-garlic paste, 1 tsp tikka masala','150 g capsicum and onion chunks','5 g oil','35 g raw rice (100 g cooked)'],
 ['Marinate fish and vegetables gently for 15–20 min.','Air-fry at 200 °C for 7–8 min, turning once.','Serve with rice and lemon.'],'Handbook p.19. Check at 6 min; fish dries fast.'),
'fishbowl':('Lunch & dinner',
 ['150 g white fish fillet','35 g raw rice (100 g cooked)','250 g mixed vegetables','5 g oil, lemon, pepper'],
 ['Pat fish dry, season with salt, pepper and lemon.','Pan-sear 3–4 min per side.','Serve over rice with the vegetables.'],'Handbook p.18, rice cut to 100 g for the rest day.'),
'palak':('Lunch & dinner · veg',
 ['200 g low-fat paneer','200 g spinach, 1 small onion, 1 tomato','1 tsp ginger-garlic paste, cumin, garam masala, chilli','5 g oil','35 g raw rice (100 g cooked)'],
 ['Blanch spinach 2 min, cool, blend smooth.','Sauté cumin, onion, paste, tomato and spices until soft.','Add the spinach purée, simmer 3 min, add paneer 2 min.'],'Handbook p.26. Regular paneer adds about 200 kcal.'),
'kadai':('Lunch & dinner · veg',
 ['200 g low-fat paneer','150 g capsicum, 1 small onion, 1 tomato (puréed)','1 tsp ginger-garlic paste, 1 tsp kadai masala (coarsely crushed coriander, chilli, cumin)','5 g oil','35 g raw rice (100 g cooked)'],
 ['Toss capsicum and onion on high heat 2–3 min; set aside.','Cook paste, tomato and kadai masala until thick.','Add paneer and vegetables, toss 2 min.'],'Handbook p.29.'),
'soyacurry':('Lunch & dinner · veg',
 ['70 g dry soya chunks','1 small onion, 1 tomato','1 tsp ginger-garlic paste, turmeric, chilli, garam masala, coriander powder','5 g oil','50 g raw rice (150 g cooked)'],
 ['Boil soya chunks 5 min, rinse in cold water, squeeze hard.','Cook onion, paste, tomato and spices into a masala.','Add soya and ½ cup water, simmer 8–10 min.'],'Handbook p.33.'),
'soyakeema':('Lunch & dinner · veg',
 ['60 g soya granules (or chopped chunks)','1 small onion, 1 tomato, 50 g green peas','1 tsp ginger-garlic paste, turmeric, chilli, garam masala','5 g oil','35 g raw rice (100 g cooked)'],
 ['Soak granules in hot water 5 min; squeeze dry.','Cook the onion-tomato masala, add granules and peas.','Cover and cook 6–8 min until dry.'],'Handbook p.35.'),
'eggbites':('Snack (swap)',
 ['4 eggs','50 g spinach, chopped','30 g low-fat cheese'],
 ['Whisk everything with salt and pepper.','Pour into silicone moulds.','Air-fry at 160 °C for 10–12 min.'],'Handbook p.41. Half a batch makes a 190 kcal snack.'),
'pepperfry':('Lunch & dinner',
 ['150 g chicken breast, cubed','70 g onion, 50 g tomato, curry leaves','1 tsp crushed black pepper, ½ tsp fennel, 1 tsp coriander powder, ½ tsp chilli, ½ tsp ginger-garlic paste','5 g oil','50 g raw rice (150 g cooked)','100 g cucumber salad'],
 ['Marinate chicken with turmeric, salt and ginger-garlic for 15 min.','Splutter fennel and curry leaves in oil, sauté onion golden, add tomato and powders.','Add chicken, cook covered 8 min, then uncovered until dry, finishing with the pepper.'],'Served with protein sambar on Wednesday.'),
'pulusu':('Lunch & dinner',
 ['150 g fish (rohu, seer, pomfret)','10 g tamarind soaked in 200 ml water','50 g onion, 2 green chillies, 100 g tomato','Turmeric, 1 tsp chilli, 1 tsp coriander powder, pinch fenugreek, curry leaves','5 g oil','50 g raw rice (150 g cooked)'],
 ['Temper mustard, fenugreek and curry leaves in oil; sauté onion and chillies.','Add tomato and powders, then the tamarind water; simmer 8 min.','Slide in the fish and simmer 8–10 min without stirring.'],'Tastes better the next day.'),
'prawn':('Lunch & dinner',
 ['150 g cleaned prawns','70 g onion, 100 g tomato, curry leaves','1 tsp ginger-garlic paste, ½ tsp pepper, ½ tsp garam masala, turmeric, chilli','5 g coconut oil','1½ chapatis (45 g atta)'],
 ['Rub prawns with turmeric, chilli and salt for 10 min.','Sauté curry leaves and onion in oil, add paste, tomato and spices until thick.','Add prawns and roast 4–5 min until just curled.'],'Overcooked prawns go rubbery; stop at 5 min.'),
'biryani':('Lunch & dinner',
 ['150 g chicken breast','60 g raw basmati, soaked 20 min','50 g curd + ginger-garlic + 1 tsp biryani masala + mint (marinade)','50 g onion, sliced; whole spices','7 g ghee','Raita: 100 g curd, 50 g cucumber, roasted cumin'],
 ['Marinate the chicken 30 min.','Fry onion golden in ghee with whole spices, add chicken and cook 10 min.','Add rice and 120 ml water, cover on the lowest heat 15 min; rest 5 min.'],'Sunday treat that still fits the numbers.'),
'sprouts':('Snack',
 ['40 g whole green moong (sprouted, about 1 cup)','20 g onion, 30 g tomato, lemon, chaat masala, coriander'],
 ['Steam the sprouts 3 min, or eat raw.','Toss with everything else.'],'Soak Saturday night; sprouts are ready by Monday.'),
'chana_bm':('Snack',
 ['30 g roasted chana','Buttermilk: 75 g curd, 200 ml water, salt, roasted cumin'],
 ['Whisk the buttermilk.','Eat the chana with it.'],''),
'fruitcurd':('Snack',
 ['1 apple','100 g Greek yogurt or hung curd'],
 ['Slice the apple and eat with the yogurt, cinnamon optional.'],'Hang 400 g curd overnight to get about 200 g.'),
'kalachana':('Snack',
 ['40 g kala chana, soaked overnight and boiled','20 g onion, 30 g tomato, lemon, chaat masala'],
 ['Toss everything together.'],''),
'eggs2':('Snack',
 ['2 eggs','100 g cucumber, pepper, salt'],['Boil 9 min, peel and season.'],''),
'makhana':('Snack',
 ['25 g makhana','2 g ghee or oil, salt, pepper','Glass of buttermilk'],
 ['Roast makhana in the ghee on low heat 5–6 min until crisp.','Season; serve with buttermilk.'],''),
}
