T_REEL = {
'okra':('Snack',
 ['150 g okra (bhindi), ends trimmed, left whole','10 g cornflour','Pinch of salt, ½ tsp garam masala, chaat masala','2 g oil spray','Glass of buttermilk'],
 ['Boil the okra in salted water for 2 min and drain well.','Toss while warm with cornflour and garam masala.','Air-fry at 200 °C for 10 min, then toss 1–2 min in a pan with the oil spray.','Dust with chaat masala.'],
 'Low in protein, so it rides with buttermilk as a snack or sits beside dal as a side.'),
'dumplings':('Lunch & dinner',
 ['200 g chicken breast','2 eggs','5–6 cabbage leaves (about 150 g), from a boiled cabbage','50 g onion, 2 garlic cloves, 1 green chilli, all finely chopped','5 g oil, salt, schezwan or green chutney to dip'],
 ['Boil the whole cabbage 10–15 min and peel off whole leaves.','Blend chicken, eggs and salt to a paste; mix in onion, garlic and chilli.','Spoon filling onto each leaf and roll into a sealed parcel.','Sear in the oiled pan on all sides, then cover and cook 8–10 min until the filling is firm.'],
 'The reel\'s single serving. No rice: 61 g protein for 506 kcal. Keep the dip to 1 tbsp.'),
'malai':('Lunch & dinner',
 ['150 g boneless chicken (half the reel\'s 300 g batch)','15 g curd, 5 g ginger-garlic paste, salt, pepper','15 g mozzarella, chopped coriander','35 g raw rice (100 g cooked) + 100 g cucumber salad'],
 ['Mix chicken with everything except rice and salad; rest 5 min in the fridge.','Air-fry at 195 °C for 15 min, pouring leftover marinade on top.','Serve with rice and salad.'],
 'Make the full 300 g batch and eat the second half on Sunday.'),
'tikkabowl':('Lunch & dinner · veg',
 ['200 g low-fat paneer, cubed','1 capsicum and 1 onion, cut into squares','50 g curd, 1 tsp coriander-cumin, 1 tsp chilli, garam masala, chaat masala, salt','5 g oil','50 g raw rice (150 g cooked)'],
 ['Coat paneer and vegetables in curd and spices.','Cook in the oiled pan, covered, 4–5 min.','Add the rice and toss until hot.'],
 'The reel says 70 g protein. That needs about 350 g paneer; this 200 g portion gives 43 g.'),
'cgfr':('Lunch & dinner · veg',
 ['150 g low-fat paneer, cubed','Paste: 5 garlic cloves, 1½ tsp chilli, 1 tsp cumin, 1 tsp garam masala, 1 tsp salt','5 g oil (the reel uses 10 g butter)','50 g onion, 150 g mixed veg (beans, carrot, corn, peas, capsicum)','50 g raw basmati (150 g cooked), coriander'],
 ['Pound the paste ingredients with a splash of water.','Fry paste and onion in oil 2 min, add paneer, then the vegetables.','Add rice and coriander; toss until coated.'],
 'The reel\'s version is 530 kcal / 33 g protein. Less fat and rice brings it to 484 kcal.'),
'kabab':('Lunch & dinner',
 ['150 g skinless chicken breast or thigh (the reel uses skin-on)','A little beaten egg (1 egg covers 500 g chicken)','1 tsp cornflour, 1–2 tsp chicken kabab masala','2 chapatis + 100 g cucumber-onion salad'],
 ['Mix chicken with egg, cornflour and masala; rest 15 min.','Air-fry at 180 °C for 18–20 min, shaking once.','Serve with chapatis and salad.'],
 'Skinless chicken saves about 150 kcal over the reel\'s skin-on pieces.'),
'greensoya':('Lunch & dinner · veg',
 ['50 g soya chunks, soaked and squeezed','60 g raw rice','Green paste: 1 cup coriander, ½ cup mint, 3 green chillies, 5 garlic, ginger, 2 cloves, small cinnamon, ½ tsp cumin, ½ tsp fennel','50 g onion, 7 g oil, garam masala, salt','100 g curd on the side'],
 ['Blend the paste with a little water.','Fry onion and soya in oil until golden (about 8 min).','Add paste and cook 3 min; add garam masala, salt, rice and 150 ml water.','Bring to a boil, cover and cook on low 15–20 min (or stir the masala into 180 g cooked rice, nati style).'],
 'Combines both soya rice reels (hariyali and nati). The reels use 2–3 tbsp oil; 7 g keeps it at 563 kcal.'),
'koreansoya':('Lunch & dinner · veg',
 ['60 g soya chunks, boiled with salt and ginger-garlic, drained','10 g rice flour, 10 g cornflour, ½ tsp chilli, 2 tsp soy sauce','Sauce: 5 g oil, 40 g onion, 2 garlic cloves, 1 tbsp gochujang (or schezwan sauce), 1 tsp ketchup, chilli, splash of water','Sesame seeds, spring onion','150 g mixed vegetables, stir-fried'],
 ['Coat the drained soya in flours, chilli and soy sauce; air-fry until crisp.','Fry onion and garlic in oil, add gochujang, ketchup, chilli and water; simmer 1 min.','Toss the soya in the sauce 2–3 min; top with sesame and spring onion.','Serve with the stir-fried vegetables.'],
 'Gochujang is in most supermarkets and online; schezwan sauce is a fine swap.'),
'eggroast':('Lunch & dinner',
 ['3 eggs + 2 egg whites, softly scrambled','Masala: 6–8 soaked byadagi chillies, 5 garlic, 5 g cashews, 1 tbsp tamarind water','Roast and grind: 1 tbsp coriander seeds, 1 tsp cumin, ½ tsp pepper, pinch methi, cinnamon, 2 cloves, curry leaves','5 g ghee (the reel uses 3–4 tbsp)','1 chapati (or 2 small neer dosas)'],
 ['Scramble the eggs and whites softly; set aside.','Dry-roast the whole spices and grind; add chillies, garlic, cashews and tamarind and grind to a paste.','Cook the paste in ghee with curry leaves until it thickens, adding water as needed.','Fold in the eggs, cover 1 min.'],
 'Cutting the ghee from 4 tbsp to 1 tsp saves about 450 kcal. Grind a double batch of masala and freeze half.'),
'pasta':('Lunch & dinner · veg',
 ['60 g dry macaroni','Sauce: 200 g low-fat paneer, 3 garlic cloves, 2 dried red chillies, 100 ml double-toned milk, salt','50 g onion, 100 g tomato','Oregano, peri-peri masala'],
 ['Cook pasta with onion, tomato, salt and just enough water until the water is absorbed.','Blend paneer, garlic, chillies, milk and salt smooth.','Stir the sauce into the pasta, cover on low 5 min.','Season with oregano and peri-peri.'],
 'The reel\'s 62 g protein covers 1–2 servings; one serving here is 49 g.'),
'corichicken':('Lunch & dinner',
 ['180 g chicken breast/thigh cubes','1 tsp cornflour, pinch baking soda, salt, pepper, dash of soy sauce','Purée: 50 g low-fat paneer (soaked 15 min), big handful coriander, 1 green chilli','5 g butter + 2 g oil, 40 g onion, lots of garlic, ½ tsp garam masala, pinch sugar','Lemon, chilli flakes; 1 chapati'],
 ['Marinate chicken 10–15 min.','Sear on high heat 3–4 min per side; set aside.','Melt butter, fry garlic and onion, add the purée and seasonings.','Return the chicken, toss, finish with lemon and chilli flakes.'],
 'Reel stated 480 kcal / 58 g protein. The stock cube is optional; it is very salty.'),
}
