# Structured ingredients for every recipe: the app computes macros and the grocery list from these.
# key -> ([(food, qty, note)], [extras]). Quantities are per serving in the food's unit (g / ml / pc / scoop).
# Extras are seasonings and serving notes that carry no meaningful calories (counted under 'spices' when they do).

# Display names for the foods table (shopping names live in export_json.INGREDIENTS).
DISPLAY = {
 'chicken':'Chicken breast, skinless (raw)', 'fish':'White fish fillet (raw)', 'prawn':'Prawns, cleaned (raw)',
 'egg_pc':'Egg', 'eggwhite_pc':'Egg white', 'paneer_lf':'Low-fat paneer', 'paneer':'Paneer',
 'curd_lf':'Low-fat curd (dahi)', 'greek':'Greek yogurt', 'milk_dt':'Double-toned milk', 'mozzarella':'Mozzarella',
 'butter':'Butter', 'whey_scoop':'Whey protein', 'onion':'Onion', 'tomato':'Tomato',
 'veg_mix':'Mixed vegetables', 'sambar_veg':'Sambar vegetables', 'spinach':'Spinach', 'capsicum':'Capsicum (bell pepper)',
 'cucumber':'Cucumber', 'peas':'Green peas', 'okra':'Okra', 'cabbage':'Cabbage', 'herbs':'Coriander & mint',
 'garlic':'Garlic', 'chilli_red':'Red chillies, fresh', 'banana_pc':'Banana', 'apple_pc':'Apple', 'guava_pc':'Guava',
 'papaya':'Papaya', 'pomegranate':'Pomegranate arils', 'rice_raw':'Rice (raw)', 'basmati_raw':'Basmati rice (raw)',
 'atta':'Whole wheat atta', 'oats':'Rolled oats', 'idli_batter':'Idli / dosa batter', 'pasta':'Macaroni (dry)',
 'toor':'Toor dal (dry)', 'moong_whole':'Whole green moong (dry)', 'moong_yellow':'Yellow moong dal (dry)',
 'soya':'Soya chunks (dry)', 'kala_chana':'Kala chana (dry)', 'roasted_chana':'Roasted chana', 'makhana':'Makhana',
 'cashew':'Cashews', 'cornflour':'Cornflour', 'ricefl':'Rice flour', 'sesame':'Sesame seeds', 'oil':'Cooking oil',
 'ghee':'Ghee', 'tamarind':'Tamarind', 'gochujang':'Gochujang', 'soysauce':'Soy sauce', 'spices':'Spices & masalas',
}

S = {
'banana':([('banana_pc',1,'medium')],['Black coffee, no sugar']),
'shake':([('whey_scoop',1,'38.5 g')],['250 ml water']),
'buttermilk':([('curd_lf',75,'whisked with 200 ml water')],['Salt, roasted cumin, curry leaves']),
'sambar':([('toor',30,''),('sambar_veg',100,'drumstick, brinjal, pumpkin, okra'),('onion',20,'or 4 shallots'),('tomato',30,''),
  ('tamarind',5,'a small marble'),('oil',3,''),('spices',5,'sambar powder, turmeric, hing')],
  ['Mustard seeds, curry leaves, 1 dried red chilli']),
'idli':([('idli_batter',150,'3 idlis'),('toor',30,'for the sambar'),('sambar_veg',100,''),('onion',20,''),('tomato',30,''),
  ('tamarind',5,''),('oil',3,''),('spices',5,'sambar powder, turmeric, hing'),('egg_pc',1,'boiled')],
  ['Sambar as in the protein sambar recipe']),
'pesarattu_p':([('moong_whole',60,'soaked 6–8 h'),('paneer',40,'grated'),('tomato',100,'for the chutney'),('oil',8,'dosa + chutney'),
  ('spices',5,'green chilli, ginger, cumin, dried red chilli')],['A little chopped onion','Salt']),
'pesarattu_e':([('moong_whole',60,'soaked 6–8 h'),('tomato',100,'for the chutney'),('oil',8,'dosa + chutney'),
  ('spices',5,'green chilli, ginger, cumin, dried red chilli'),('egg_pc',1,'boiled, or cracked over the dosa')],['Salt']),
'bhurji':([('egg_pc',2,''),('eggwhite_pc',3,''),('onion',50,''),('tomato',50,''),('oil',3,''),('atta',30,'1 chapati, no ghee')],
  ['1 green chilli, pinch turmeric, ½ tsp chilli powder, coriander leaves']),
'chilla':([('moong_yellow',60,'soaked 2–3 h'),('paneer_lf',50,'crumbled'),('onion',20,''),('oil',5,''),('curd_lf',100,'on the side')],
  ['Pinch cumin and chilli, salt']),
'oatsbowl':([('oats',65,''),('greek',100,'or hung curd'),('pomegranate',100,''),('egg_pc',1,'boiled')],[]),
'oatswhey':([('oats',50,''),('milk_dt',200,''),('whey_scoop',1,'38.5 g'),('papaya',150,'on the side')],['Cinnamon']),
'chx_rice':([('chicken',150,''),('rice_raw',50,'150 g cooked'),('veg_mix',250,''),('oil',5,'')],['½ tsp cumin or paprika, salt, pepper']),
'chx_chapati':([('chicken',150,''),('atta',60,'2 chapatis'),('veg_mix',250,''),('oil',5,'')],['Spices, salt']),
'tandoori':([('chicken',150,'breast or thigh'),('curd_lf',100,''),('oil',5,''),('rice_raw',50,'150 g cooked'),
  ('spices',5,'tandoori masala, turmeric, ginger-garlic paste')],['Juice of ½ lemon, salt']),
'tikkamasala':([('chicken',150,''),('onion',70,'1 small'),('tomato',150,'puréed'),('curd_lf',30,''),('cashew',10,'soaked, blended'),
  ('oil',5,''),('rice_raw',35,'100 g cooked'),('spices',5,'ginger-garlic paste, garam masala, chilli')],['Kasuri methi, salt']),
'keema':([('chicken',150,'lean mince'),('onion',70,'1 small'),('tomato',100,'1 medium'),('peas',50,''),('oil',5,''),('rice_raw',35,'100 g cooked'),
  ('spices',5,'ginger-garlic paste, turmeric, chilli, garam masala')],['Salt']),
'fishtikka':([('fish',150,'seer / vanjaram or basa'),('curd_lf',100,''),('capsicum',75,'chunks'),('onion',75,'chunks'),('oil',5,''),
  ('rice_raw',35,'100 g cooked'),('spices',5,'ginger-garlic paste, tikka masala')],['Salt, lemon']),
'fishbowl':([('fish',180,'raw, about 150 g cooked'),('rice_raw',35,'100 g cooked'),('veg_mix',250,''),('oil',5,'')],['Lemon, pepper, salt']),
'palak':([('paneer_lf',200,''),('spinach',200,''),('onion',70,'1 small'),('tomato',100,'1 medium'),('oil',5,''),('rice_raw',35,'100 g cooked'),
  ('spices',5,'ginger-garlic paste, cumin, garam masala, chilli')],['Salt']),
'kadai':([('paneer_lf',200,''),('capsicum',150,''),('onion',70,'1 small'),('tomato',100,'puréed'),('oil',5,''),('rice_raw',35,'100 g cooked'),
  ('spices',5,'ginger-garlic paste, kadai masala')],['Kadai masala: coarsely crushed coriander, chilli, cumin']),
'soyacurry':([('soya',70,''),('onion',70,'1 small'),('tomato',100,'1 medium'),('oil',5,''),('rice_raw',50,'150 g cooked'),
  ('spices',5,'ginger-garlic paste, turmeric, chilli, garam masala, coriander')],['Salt']),
'soyakeema':([('soya',60,'granules or chopped chunks'),('onion',70,'1 small'),('tomato',100,'1 medium'),('peas',50,''),('oil',5,''),
  ('rice_raw',35,'100 g cooked'),('spices',5,'ginger-garlic paste, turmeric, chilli, garam masala')],['Salt']),
'eggbites':([('egg_pc',4,''),('spinach',50,'chopped'),('mozzarella',30,'or low-fat cheese')],['Salt, pepper']),
'pepperfry':([('chicken',150,'cubed'),('onion',70,''),('tomato',50,''),('oil',5,''),('rice_raw',50,'150 g cooked'),('cucumber',100,'salad'),
  ('spices',10,'black pepper, fennel, coriander, chilli, ginger-garlic')],['Curry leaves, salt']),
'pulusu':([('fish',150,'rohu, seer or pomfret'),('tamarind',10,'soaked in 200 ml water'),('onion',50,''),('tomato',100,''),('oil',5,''),
  ('rice_raw',50,'150 g cooked'),('spices',10,'turmeric, chilli, coriander, fenugreek')],['2 green chillies, curry leaves, salt']),
'prawn':([('prawn',150,''),('onion',70,''),('tomato',100,''),('oil',5,'coconut oil'),('atta',45,'1½ chapatis'),
  ('spices',10,'ginger-garlic paste, pepper, garam masala, turmeric, chilli')],['Curry leaves, salt']),
'biryani':([('chicken',150,''),('basmati_raw',60,'soaked 20 min'),('curd_lf',150,'50 g marinade + 100 g raita'),('onion',50,'sliced'),
  ('ghee',7,''),('cucumber',50,'for the raita'),('spices',10,'ginger-garlic, biryani masala, whole spices')],['Mint, roasted cumin, salt']),
'sprouts':([('moong_whole',40,'sprouted, about 1 cup'),('onion',20,''),('tomato',30,'')],['Lemon, chaat masala, coriander']),
'chana_bm':([('roasted_chana',30,''),('curd_lf',75,'buttermilk with 200 ml water')],['Salt, roasted cumin']),
'fruitcurd':([('apple_pc',1,''),('greek',100,'or hung curd')],[]),
'kalachana':([('kala_chana',40,'soaked overnight and boiled'),('onion',20,''),('tomato',30,'')],['Lemon, chaat masala']),
'eggs2':([('egg_pc',2,'boiled'),('cucumber',100,'')],['Pepper, salt']),
'makhana':([('makhana',25,''),('oil',2,'or ghee'),('curd_lf',75,'glass of buttermilk')],['Salt, pepper']),
'okra':([('okra',150,'ends trimmed, left whole'),('cornflour',10,''),('oil',2,'spray'),('spices',3,'garam masala, chaat masala'),
  ('curd_lf',75,'glass of buttermilk')],['Pinch of salt']),
'dumplings':([('chicken',200,''),('egg_pc',2,''),('cabbage',150,'5–6 leaves from a boiled cabbage'),('onion',50,'finely chopped'),
  ('garlic',10,'2 cloves'),('oil',5,''),('spices',5,'green chilli, salt')],['Schezwan or green chutney to dip (1 tbsp)']),
'malai':([('chicken',150,'boneless, half the reel\'s 300 g batch'),('curd_lf',15,''),('garlic',5,'ginger-garlic paste'),('mozzarella',15,''),
  ('herbs',10,'chopped coriander'),('rice_raw',35,'100 g cooked'),('cucumber',100,'salad')],['Salt, pepper']),
'tikkabowl':([('paneer_lf',200,'cubed'),('capsicum',120,'1, in squares'),('onion',100,'1, in squares'),('curd_lf',50,''),('oil',5,''),
  ('rice_raw',50,'150 g cooked'),('spices',10,'coriander-cumin, chilli, garam masala, chaat masala')],['Salt']),
'cgfr':([('paneer_lf',150,'cubed'),('garlic',15,'5 cloves'),('oil',5,'the reel uses 10 g butter'),('onion',50,''),
  ('veg_mix',150,'beans, carrot, corn, peas, capsicum'),('rice_raw',50,'basmati, 150 g cooked'),('spices',10,'chilli, cumin, garam masala')],
  ['1 tsp salt, coriander leaves']),
'kabab':([('chicken',150,'skinless breast or thigh'),('egg_pc',0.3,'a little beaten egg'),('cornflour',3,'1 tsp'),('spices',5,'chicken kabab masala'),
  ('atta',60,'2 chapatis'),('cucumber',100,'cucumber-onion salad')],[]),
'greensoya':([('soya',50,'soaked and squeezed'),('rice_raw',60,''),('onion',50,''),('oil',7,''),('herbs',40,'1 cup coriander, ½ cup mint'),
  ('garlic',10,'5 cloves'),('spices',5,'green chillies, ginger, whole spices, cumin, fennel, garam masala'),('curd_lf',100,'on the side')],['Salt']),
'koreansoya':([('soya',60,'boiled with salt and ginger-garlic'),('ricefl',10,''),('cornflour',10,''),('soysauce',10,'2 tsp'),('oil',5,''),
  ('onion',40,''),('garlic',10,'2 cloves'),('gochujang',15,'1 tbsp, or schezwan sauce'),('sesame',3,''),('veg_mix',150,'stir-fried')],
  ['½ tsp chilli, 1 tsp ketchup, spring onion, splash of water']),
'eggroast':([('egg_pc',3,'softly scrambled'),('eggwhite_pc',2,''),('ghee',5,'the reel uses 3–4 tbsp'),('cashew',5,''),('garlic',10,'5 cloves'),
  ('tamarind',5,'1 tbsp tamarind water'),('spices',15,'byadagi chillies, coriander seeds, cumin, pepper, methi, cinnamon, cloves'),
  ('atta',30,'1 chapati, or 2 small neer dosas')],['Curry leaves']),
'pasta':([('pasta',60,''),('paneer_lf',200,'for the sauce'),('milk_dt',100,''),('onion',50,''),('tomato',100,''),('garlic',15,'3 cloves'),
  ('spices',5,'dried red chillies, oregano, peri-peri')],['Salt']),
'corichicken':([('chicken',180,'breast or thigh cubes'),('paneer_lf',50,'soaked 15 min, for the purée'),('cornflour',5,'1 tsp'),('butter',5,''),
  ('oil',2,''),('onion',40,''),('garlic',10,'lots'),('herbs',30,'big handful coriander'),('atta',30,'1 chapati')],
  ['1 green chilli, pinch baking soda, salt, pepper, dash of soy sauce, ½ tsp garam masala, pinch sugar, lemon, chilli flakes']),
'grillbowl':([('chicken',200,'cut or lightly scored'),('greek',100,'for the marinade'),('butter',10,'for grilling'),('capsicum',50,''),
  ('cucumber',100,'chopped'),('onion',20,'sliced'),('egg_pc',2,'boiled'),('garlic',12,'4 cloves, for the paste'),('chilli_red',6,'2, for the paste'),
  ('spices',5,'chilli, turmeric, black pepper, cumin, coriander, garam masala')],
  ['Salt','Optional: lemon juice, chilli flakes, fresh coriander']),
}
